name: Python package

on: [push]
jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/checkout@v3
        with:
          python-version: "3.10"
      - name: Run Tests
        run: python -m unittest
